server:
  port: 8080

spring:
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
#    password: Abc.123456
    port : 6379
    username: default
    database: 2

smb:
  host: 183.134.170.168
  username: admin
  password: admin
  share: DATA
  libraryDir: 视觉素材库/视觉素材库.library
